version: '3.7'

x-app: &app
  build:
    context: .
    dockerfile: ./Dockerfile
  image: hold-my-dog:0.0.1
  tmpfs:
    - /tmp
  stdin_open: true
  tty: true
  volumes:
    - .:/app:cached
    - rails_cache:/app/tmp/cache
    - bundle:/bundle
    - node_modules:/app/node_modules
    - packs:/app/public/packs
  environment:
    - REDIS_URL=redis://redis:6379
    - DATABASE_URL=postgres://postgres:postgres@postgres:5432
    - YARN_CACHE_FOLDER=/app/node_modules/.yarn-cache
    - BOOTSNAP_CACHE_DIR=/usr/local/bundle/_bootsnap

services:
  console:
    <<: *app
    command: /bin/bash

  rails:
    <<: *app
    command: bundle exec rails server -b 0.0.0.0 -p 3000
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:13.3-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s

  redis:
    image: redis:6.2.5-alpine
    volumes:
      - redis:/data
    ports:
      - '6379:6379'
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  postgres:
  redis:
  bundle:
  node_modules:
  rails_cache:
  packs: