default: &default
  adapter: postgresql
  database: statusbackend_production
  username: 
  password:  <%= ENV['MYAPP_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: holdmydog_development

test:
  <<: *default
  database: holdmydog_test

production:
  <<: *default
  database: holdmydog_production
